### ISSUE TITLE
Disabling Lightning and bats in config

### ISSUE THREAD

**Issue by Chaka15205** [mbax/VanishNoPacket#621]
Can this please be added

**Comment by mbax** [comment]
Lightning and bats (and other effects) are disabled by default. They only occur on login if you specifically grant the permission nodes. 

Adding a second set of ways to disable them, especially when they're disabled by default, would be counterproductive.

**Comment by Chaka15205** [comment]
Yes, But people give them * permissions and I am not the only one who complains about there not being a config option to disable effects.

**Comment by mbax** [comment]
The only reason to grant the '*' node is because you want every single permission node. You clearly do not.

I think what you're actually looking for is granting yourself OP. With OP, you get every single permission node **except** the ones that plugin authors such as myself have defined as "do not grant this to OP."
