### ISSUE TITLE
RE: VanishNoPacket (1.9 support)

### ISSUE THREAD

**Issue by Chalwk77** [mbax/VanishNoPacket#641]
Hello.

Will you be updating VanishNoPacket to be compatible with Spigot 1.9?

**Comment by mbax** [comment]
VNP is fully functional on the latest Bukkit API. It needs no further updates unless an unofficial server mod fork deliberately breaks it.

**Comment by EvilOlaf** [comment]
To prevent any unnecessary followups: The development of the original Bukkit API has been discontinued due to a DCMA takedown notice.
The Bukkit API you know from Spigot is not the original, it is a fork which is moving in kind a legal limbo.
Some developers are not willing to support this fork for comprehensible reasons.

If you want VNP to work with any other API than the original Bukkit API you have to fix this at your own.

**Comment by mbax** [comment]
Any other API isn't entirely true. Early, functional builds of Vanish for Sponge are available: https://github.com/KittehOrg/Vanish

**Comment by EvilOlaf** [comment]
Yes, I am sorry. Sponge is supported of course ;)

**Comment by mbax** [comment]
Viva la Sponge!
