### ISSUE TITLE
Fancy pants

### ISSUE THREAD

**Issue by MithrandirCraft** [mbax/VanishNoPacket#646]
Players can see me on tab, allthough I am vanished.

---------------------------
Spigot 1.9
VNP: 3.20

**Comment by TheMolkaPL** [comment]
VanishNoPacket is a __Bukkit__, not a Spigot plugin.

**Comment by mbax** [comment]
Those are some nice pants. Sounds like Spigot broke stuff again!

**Comment by MithrandirCraft** [comment]
@TheMolkaPL So this plugin only works whith an API that doesn't exist.

Good job.

**Comment by TheMolkaPL** [comment]
No, [Bukkit exists here](https://github.com/Bukkit/Bukkit). It's the Spigot Team that breaks everything in it.

**Comment by mbax** [comment]
@MithrandirCraft This plugin works with the Bukkit API. Spigot's implementation of that API is broken. Judging by your report, the API itself related to this wasn't broken, meaning that it is still compatible with Spigot, but rather their implementation is missing that piece.

**Comment by MithrandirCraft** [comment]
Understood, that seems sensible.

**Comment by MithrandirCraft** [comment]
However, if your plugin is designed for Bukkit, there are going to be quite a few reports coming from Spigot. Maybe you should explicitly state that it's a Bukkit exclusive plugin. If what @TheMolkaPL says is the case.

**Comment by mbax** [comment]
"Designed for Bukkit" is the case of like 80% of the plugins folks still use on their servers. Spigot's API is rather minimal and most plugins don't depend on it at all.

It's not exclusive, it's just a Bukkit plugin where Bukkit is the API used. The problem you're experiencing would happen if I specifically "designed" this for Spigot's mediocre continuation of Bukkit, because I'd be using the exact same code. I'd just change what jar I build against and that wouldn't affect anything. The resulting VNP jar would be 100% identical.  The issue lies with Spigot breaking something again. They also broke vanishing on 1.8 at least once, judging by reports I got around then.
