### ISSUE TITLE
Vanish Fake Announce

### ISSUE THREAD

**Issue by SmartTV20011** [mbax/VanishNoPacket#655]
So basically when ever me or my staff do /v fj it says "PLAYER joined the game" that works fine however it only shows up to the people that can use vanish. To regular players it does not show the join or leave message. I don't know if there is a permission node that I don't know about or something.
![capture](https://cloud.githubusercontent.com/assets/24781432/21485989/c256a7c4-cb71-11e6-835c-46f6dd4e4378.PNG)
So i had my alt account on my server and I basically had him set to a regular player and as you could see there i get a message saying i joined or left and my alt doesn't. If you could please respond to me and let me know why this is happening that would be great!
Thanks, love your plugin!

**Comment by mbax** [comment]
That... shouldn't happen. What permissions plugin are you using, and what version is it?

**Comment by SmartTV20011** [comment]
I'm using pex 1.23.4

**Comment by mbax** [comment]
I was hoping you were on a super old PEX, because there had been a PEX bug where broadcasts (which is how that fake join message is sent, meaning it *can't* be only showing to some people) didn't get sent to some players. Are you able to do me a quick favor and test (separately, to not break your server) just VanishNoPacket with a friend, to see if this still happens when one of you is OP and the other isn't (with no other plugins)? You'll have to add this to the permissions.yml in the server root (not PEX): 

```yaml
testing.test:
       description: oh no
       default: op
       children:
          vanish.standard: true
```

**Comment by SmartTV20011** [comment]
Sure I will

**Comment by SmartTV20011** [comment]
Sure I will

**Comment by SmartTV20011** [comment]
So this time it worked perfectly... with the permission.yml thing
![capture](https://cloud.githubusercontent.com/assets/24781432/21504741/0df1a11a-cc27-11e6-8ca7-e0e2d7f9adb2.PNG)
But then i tested it with pex too and it worked perfectly aswell...
![capture pngfgd](https://cloud.githubusercontent.com/assets/24781432/21504749/1c03b658-cc27-11e6-893a-9766ec75798e.PNG)
I should have tested it before I bothered you, sorry about that, it must be another plugin on my server doing it :(

**Comment by mbax** [comment]
Thanks for testing it! This is... weird. 

Fastest way to narrow down the plugin:

With PEX and VNP always there, add *half* your plugins. If it still works, the problem is in the other half. If it doesn't work, the problem is in this half.

Remove all plugins except PEX and VNP. Now, add half the plugins from the group where it broke. If it breaks again, it's in that group. If not, it's in the half you didn't add. 

Repeat until you narrow it down to one plugin. 

I'd be interested in knowing what is causing it. :)

**Comment by SmartTV20011** [comment]
I will do some testing on this... and i will give you a reply.

**Comment by SmartTV20011** [comment]
So I did the test, first I put all the plugins on a localhost server, and then it worked perfectly so it has nothing to do with the plugins I have on my server might just be something else on my server, so there's nothing for you to worry about.

**Comment by SmartTV20011** [comment]
I actually figured out why this was happening...
I had the permissions
 - -bukkit.*
 - -minecraft.*
for my default group, once i removed those it worked fine.

**Comment by SmartTV20011** [comment]
by doing that it removed the permission node, bukkit.broadcast which is for " 	Allows the user to receive all broadcast messages. " and that is why it didnt work.... again sorry for creating the trouble...

**Comment by mbax** [comment]
Oh man, I forgot that permission even existed! Well, there you have it. Mystery solved.

Don't worry about trouble. Things have been rather quiet for me since Bukkit shut down. :)
