### ISSUE TITLE
The plugin is alive?

### ISSUE THREAD

**Issue by Superdarco** [mbax/VanishNoPacket#667]
Hi, I just want to know if the plugin is still in development, Regards.

**Comment by Zarthus** [comment]
Based on this being a bukkit plugin, and bukkit not being alive: No.

**Comment by mbax** [comment]
A few useful points!

1. This plugin hasn't really needed an update in 4 years.
2. Bukkit died 4 years ago.
3. This plugin still works great, according to dozens of people who regularly check in to tell me how happy they are it still works great!
4. Check out [Sponge](https://www.spongepowered.org/), a modern alternative/replacement to Bukkit. It has plugins *and* no legal concerns! 
5. I'm closing this issue because it has been answered, but don't let that stop you from replying.

**Comment by Superdarco** [comment]
Yes, bukkit died, but spigot is replacing it.

**Comment by Superdarco** [comment]
And it's practically the same, but better.

**Comment by mbax** [comment]
See item 4, part 2. Legal concerns. Spigot's continued publishing of what they publish is a US copyright law issue. Plus, they've done a shit job actually improving it. It's basically the same API we (hi, I was one of the Bukkit team folks) had for 1.6 (and were hoping to scrap by 1.8) back in 2013 and that's really not a good state to be in for 2018. Better for 2013/2014? Sure maybe. Better for 2018? Nah.

Sponge, on the other hand, has been designed for the newer features in Minecraft. Plus, as an added bonus, you can (don't have to) run it alongside mods! Fancy stuff.
